config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "daily_posts" => "users#daily_posts"
  end
  get "searches" => "searches#search"

  resources :chats, only: [:show, :create]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

  resources :stopwatches, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags, source: :tag
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :created_today, -> {where(created_at: Time.current.all_day)}
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  scope :created_2day_ago, -> {where(created_at: 2.day.ago.all_day)}
  scope :created_3day_ago, -> {where(created_at: 3.day.ago.all_day)}
  scope :created_4day_ago, -> {where(created_at: 4.day.ago.all_day)}
  scope :created_5day_ago, -> {where(created_at: 5.day.ago.all_day)}
  scope :created_6day_ago, -> {where(created_at: 6.day.ago.all_day)}

  scope :created_this_week, -> {where(created_at: 6.day.ago.at_beginning_of_day..Time.current.at_end_of_day)}
  scope :created_last_week, -> {where(created_at: 2.week.ago.at_beginning_of_day..1.week.ago.at_end_of_day)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(savebook_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savebook_tags
    new_tags = savebook_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name: new_name)
      self.tags << book_tag
    end
  end

  def self.search_for(content, method)
    if method == "perfect"
      Book.where("title LIKE?", "#{content}")
    elsif method == "forward"
      Book.where("title LIKE?", "#{content}%")
    elsif method == "backward"
      Book.where("title LIKE?", "%#{content}")
    elsif method == "partial"
      Book.where("title LIKE?", "%#{content}%")
    else
      Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: {maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  has_one_attached :group_image

  validates :name, presence: true
  validates :introduction, presence: true

  def get_group_image
    (group_image.attached?)? group_image : "no_image.jpg"
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/stopwatch.rb
class Stopwatch < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags, source: :book

  def self.search_books_for(content, method)
    if method == "perfect"
      tags = Tag.where("name LIKE ?", "#{content}")
    elsif method == "forward"
      tags = Tag.where("name LIKE ?", "#{content}%")
    elsif method == "backward"
      tags = Tag.where("name LIKE ?", "%#{content}")
    else
      tags = Tag.where("name LIKE ?", "%#{content}%")
    end

    return tags.inject(init = []){|result, tag| result + tag.books}

# ーーーーーeach文に書き換えーーーーーーーー
    # result = []
    # tags.each do |tag|
    #   result = result += tag.books
    # end

    # return result
# ーーーーーーーーーーーーーーーーーーーーー

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: "follower"
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: "following"
  has_many :user_rooms
  has_many :chats
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :stopwatches
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def followed_by?(user)
    reverse_of_relationships.exists?(following_id: user.id)
  end

  def self.search_for(content, method)
    if method == "perfect"
      User.where("name LIKE?", "#{content}")
    elsif method == "forward"
      User.where("name LIKE?", "#{content}%")
    elsif method == "backward"
      User.where("name LIKE?", "%#{content}")
    elsif method == "partial"
      User.where("name LIKE?", "%#{content}%")
    else
      User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      @group_user = current_user.group_users.new(group_id: @group.id)
      @group_user.save
      redirect_to groups_path
    else
      render :new
    end

  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    redirect_to groups_path unless @group.owner_id == current_user.id
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group do |f| %>
  <div class="form-group">
    <label for="name">グループ名</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="introduction">紹介文</label>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="group_image">グループ画像</label>
    <%= f.file_field :group_image, accept: "image/*", class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Group</h2>
    <%= render "layouts/errors", obj: @group %>
    <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td><%= image_tag group.get_group_image, size: "100x100" %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td><%= group.group_users.count %></td>
            <td>
              <% if group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(group), class: "btn btn-success btn-sm" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= render "layouts/errors", obj: @group %>
    <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <td><%= image_tag @group.get_group_image, size: "50x50" %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group.users.each do |user| %>
              <%= user.name %><br>
            <% end %>
          </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(@group), class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Notice an Event", new_group_event_notice_path(@group), class: "btn btn-info btn-sm" %></td>
            <% else %>
              <% if @group.includesUser?(current_user) %>
                <td><%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-danger btn-sm" %></td>
              <% else %>
                <td><%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-success btn-sm" %></td>
              <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>