config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "daily_posts" => "users#daily_posts"
  end
  get "searches" => "searches#search"

  resources :chats, only: [:show, :create]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

  resources :stopwatches, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags, source: :tag
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :created_today, -> {where(created_at: Time.current.all_day)}
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  scope :created_2day_ago, -> {where(created_at: 2.day.ago.all_day)}
  scope :created_3day_ago, -> {where(created_at: 3.day.ago.all_day)}
  scope :created_4day_ago, -> {where(created_at: 4.day.ago.all_day)}
  scope :created_5day_ago, -> {where(created_at: 5.day.ago.all_day)}
  scope :created_6day_ago, -> {where(created_at: 6.day.ago.all_day)}

  scope :created_this_week, -> {where(created_at: 6.day.ago.at_beginning_of_day..Time.current.at_end_of_day)}
  scope :created_last_week, -> {where(created_at: 2.week.ago.at_beginning_of_day..1.week.ago.at_end_of_day)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(savebook_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savebook_tags
    new_tags = savebook_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name: new_name)
      self.tags << book_tag
    end
  end

  def self.search_for(content, method)
    if method == "perfect"
      Book.where("title LIKE?", "#{content}")
    elsif method == "forward"
      Book.where("title LIKE?", "#{content}%")
    elsif method == "backward"
      Book.where("title LIKE?", "%#{content}")
    elsif method == "partial"
      Book.where("title LIKE?", "%#{content}%")
    else
      Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: {maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  has_one_attached :group_image

  validates :name, presence: true
  validates :introduction, presence: true

  def get_group_image
    (group_image.attached?)? group_image : "no_image.jpg"
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/stopwatch.rb
class Stopwatch < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags, source: :book

  def self.search_books_for(content, method)
    if method == "perfect"
      tags = Tag.where("name LIKE ?", "#{content}")
    elsif method == "forward"
      tags = Tag.where("name LIKE ?", "#{content}%")
    elsif method == "backward"
      tags = Tag.where("name LIKE ?", "%#{content}")
    else
      tags = Tag.where("name LIKE ?", "%#{content}%")
    end

    return tags.inject(init = []){|result, tag| result + tag.books}

# ーーーーーeach文に書き換えーーーーーーーー
    # result = []
    # tags.each do |tag|
    #   result = result += tag.books
    # end

    # return result
# ーーーーーーーーーーーーーーーーーーーーー

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: "follower"
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: "following"
  has_many :user_rooms
  has_many :chats
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :stopwatches
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def followed_by?(user)
    reverse_of_relationships.exists?(following_id: user.id)
  end

  def self.search_for(content, method)
    if method == "perfect"
      User.where("name LIKE?", "#{content}")
    elsif method == "forward"
      User.where("name LIKE?", "#{content}%")
    elsif method == "backward"
      User.where("name LIKE?", "%#{content}")
    elsif method == "partial"
      User.where("name LIKE?", "%#{content}%")
    else
      User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def daily_posts
    user = User.find(params[:user_id])
    if params[:created_at] == ""
      render :daily_posts_error
    else
      @books = user.books.where(created_at: params[:created_at].to_date.all_day)
      render :daily_posts_form
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <% if user.followed_by?(current_user) %>
          <td><%= link_to "フォロー外す", user_relationships_path(user), method: :delete %></td>
        <% else %>
          <td><%= link_to "フォローする", user_relationships_path(user), method: :post %></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if user.followed_by?(current_user) %>
      <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info btn-sm" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success btn-sm" %>
    <% end %>
  <% end %>

  <% if (user != current_user) && (user.followed_by?(current_user)) && (current_user.followed_by?(user)) %>
    <%= link_to "chatを始める", chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

app/views/users/daily_posts_error.js.erb
$('.daily_posts_table').html('日付を選択してください')

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-bordered">
        <thead>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </thead>
        <tbody>
          <td><%=@today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <td>
            <% if @yesterday_book.count == 0 %>
              前日の投稿が0のため計算できません
            <% else %>
              <% (@the_day_before = @today_book.count / @yesterday_book.count).to_f %>
              <%= (@the_day_before * 100).round %>%
            <% end %>
          </td>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <th>今週の投稿数</th>
          <th>先週の投稿数</th>
          <th>前週比</th>
        </thead>
        <tbody>
          <td><%=@this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <td>
            <% if @last_week_book.count == 0 %>
              前週の投稿が0のため計算できません
            <% else %>
              <% (@the_week_before = @this_week_book.count / @last_week_book.count).to_f %>
              <%= (@the_week_before * 100).round %>%
            <% end %>
          </td>
        </tbody>
      </table>
      <h2>7日間分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </thead>
        <tbody>
          <td><%= @books.created_6day_ago.count %></td>
          <td><%= @books.created_5day_ago.count %></td>
          <td><%= @books.created_4day_ago.count %></td>
          <td><%= @books.created_3day_ago.count %></td>
          <td><%= @books.created_2day_ago.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_today.count %></td>
        </tbody>
      </table>
      <%= line_chart @books.group_by_day(:created_at, last: 7).count %>
      <%= render "daily_posts_form", user: @user %>

    </div>
  </div>
</div>